
//Menu Laterale
document.write('<nav class="white" role="navigation">');
document.write('<div class="nav-wrapper container">');
document.write('<a id="logo-container" href="home.html" class="brand-logo">La fausto Coppi</a>');
document.write('<ul id="slide-out" class="side-nav">');
document.write('<li><a href="home.html">Home</a></li>');
document.write('<li class="no-padding">');
document.write('<ul class="collapsible collapsible-accordion">');
document.write('<li>');
document.write('<a class="collapsible-header">Edizione 2018<i class="material-icons">arrow_drop_down</i></a>');
document.write('<div class="collapsible-body">');
document.write('<ul>');
document.write('<li><a href="includes/regolamento.html">Regolamento</a></li>');
document.write('<li><a href="includes/iscriversi.html">Come iscriversi</a></li>');
document.write('<li><a href="includes/domande.html">Domande frequenti - FAQs</a></li>');
document.write('<li><a href="includes/dateRicordare.html">Date da ricordare</a></li>');
document.write('<li><a href="includes/hotel.html">Hotel / B&amp;B / Camper</a></li>');
document.write('<li><a href="includes/affittaBici.html">Affitta una bici</a></li>');
document.write('<li><a href="includes/operatore.html">Tour Operator</a></li>');
document.write('<li><a href="includes/volontario.html">Diventa volontario</a></li>');
document.write('<li><a href="includes/mangiaPedale.html">La Mangia e Pedale</a></li>');
document.write('</ul>');
document.write('</div>');document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="no-padding">');
document.write('<ul class="collapsible collapsible-accordion">');
document.write('<li>');
document.write('<a class="collapsible-header">Percorsi<i class="material-icons">arrow_drop_down</i></a>');
document.write('<div class="collapsible-body">');
document.write('<ul>');
document.write('<li><a href="includes/salite.html">Salite</a></li>');
document.write('<li><a href="includes/tabelleMarcia.html">Tabelle di marcia</a></li>');
document.write('<li><a href="includes/ristori.html">Ristori</a></li>');
document.write('</ul>');
document.write('</div>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li><a href="includes/cuneo.html">Cuneo</a></li>');
document.write('<li class="no-padding">');
document.write('<ul class="collapsible collapsible-accordion">');
document.write('<li>');
document.write('<a class="collapsible-header">Classifiche<i class="material-icons">arrow_drop_down</i></a>');
document.write('<div class="collapsible-body">');
document.write('<ul>');
document.write('<li><a href="includes/edizione2017.html">Edizione 2017</a></li>');
document.write('<li><a href="includes/edizione2016.html">Edizione 2016</a></li>');
document.write('<li><a href="includes/edizione2015.html">Edizione 2015</a></li>');
document.write('<li><a href="includes/edizione2014.html">Edizione 2014</a></li>');
document.write('<li><a href="includes/edizione2013.html">Edizione 2013</a></li>');
document.write('<li><a href="includes/edizionePrec.html">Edizioni precedenti</a></li>');
document.write('</ul>');
document.write('</div>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li><a href="includes/maglie.html">Maglie</a></li>');
document.write('<li class="no-padding">');
document.write('<ul class="collapsible collapsible-accordion">');
document.write('<li>');
document.write('<a class="collapsible-header">Circuiti<i class="material-icons">arrow_drop_down</i></a>');
document.write('<div class="collapsible-body">');
document.write('<ul>');
document.write('<li><a href="includes/circuitoPrestigio.html">Circuito Prestigio 2018</a></li>');
document.write('<li><a href="includes/trofeoAlpi.html">Trofeo delle Alpi</a></li>');
document.write('</ul>');
document.write('</div>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li><a href="includes/news.html">News</a></li>');
document.write('<li><a href="includes/contatti.html">Contatti</a></li>');
document.write('</ul>');
document.write('<!-- Menu classico-->');
document.write('<ul class="right hide-on-med-and-down">');
document.write('<li><a href="home.html">Home</a></li>');
document.write('<li><a class="dropdown-button" href="#!" data-activates="dropdown1">Edizione 2018<i class="material-icons right">arrow_drop_down</i></a></li>');
document.write('<ul id="dropdown1" class="dropdown-content">');
document.write('<li><a href="includes/regolamento.html">Regolamento</a></li>');
document.write('<li><a href="includes/iscriversi.html">Come iscriversi</a></li>');
document.write('<li><a href="includes/domande.html">Domande frequenti - FAQs</a></li>');
document.write('<li><a href="includes/dateRicordare.html">Date da ricordare</a></li>');
document.write('<li><a href="includes/hotel.html">Hotel / B&amp;B / Camper</a></li>');
document.write('<li><a href="includes/affittaBici.html">Affitta una bici</a></li>');
document.write('<li><a href="includes/operatore.html">Tour Operator</a></li>');
document.write('<li><a href="includes/volontario.html">Diventa volontario</a></li>');
document.write('<li><a href="includes/mangiaPedala.html">La Mangia e Pedale</a></li>');
document.write('</ul>');
document.write('<li><a class="dropdown-button" href="#!" data-activates="dropdown1">Percorsi<i class="material-icons right">arrow_drop_down</i></a></li>');
document.write('<ul id="dropdown1" class="dropdown-content">');
document.write('<li><a href="includes/salite.html">Salite</a></li>');
document.write('<li><a href="includes/tabelleMarcia.html">Tabelle di marcia</a></li>');
document.write('<li><a href="includes/ristori.html">Ristori</a></li>');
document.write('</ul>');
document.write('<li><a href="includes/cuneo.html">Cuneo</a></li>');
document.write('<li><a class="dropdown-button" href="#!" data-activates="dropdown1">Classifiche<i class="material-icons right">arrow_drop_down</i></a></li>');
document.write(' <ul id="dropdown1" class="dropdown-content">');
document.write('<li><a href="includes/edizione2017.html">Edizione 2017</a></li>');
document.write('<li><a href="includes/edizione2016.html">Edizione 2016</a></li>');
document.write('<li><a href="includes/edizione2015.html">Edizione 2015</a></li>');
document.write('<li><a href="includes/edizione2014.html">Edizione 2014</a></li>');
document.write('<li><a href="includes/edizione2013.html">Edizione 2013</a></li>');
document.write('<li><a href="includes/edizionePrec.html">Edizioni Precedenti></li>');
document.write('</ul>');
document.write('<li><a href="includes/maglie.html">Maglie</a></li>');
document.write('');
document.write('<li><a class="dropdown-button" href="#!" data-activates="dropdown1">Circuiti<i class="material-icons right">arrow_drop_down</i></a></li>');
document.write(' <ul id="dropdown1" class="dropdown-content">');
document.write('<li><a href="includes/circuitoPrestigio.html">Circuito Prestigio 2018</a></li>');
document.write('<li><a href="includes/trofeoAlpi.html">Trofeo delle Alpi</a></li>');
document.write('</ul>');
document.write('<li><a href="includes/news.html">News</a></li>');
document.write('<li><a href="includes/contatti.html">Contatti</a></li>');
document.write('</ul>');
document.write('<a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>');
document.write('</nav>');
