
//Menu Laterale
document.write('<nav class="white" role="navigation">');
document.write('<div class="nav-wrapper container">');
document.write('<a id="logo-container" href="../index.html" class="brand-logo"><center><img style="width:70%; height: 70%;" src="../images/straight_logo.png"></center></a>');
document.write('<ul id="slide-out" class="side-nav">');
document.write('<li><a href="../index.html">Home</a></li>');
document.write('<li class="no-padding">');
document.write('<ul class="collapsible collapsible-accordion">');
document.write('<li>');
document.write('<a class="collapsible-header">Edizione 2018<i><img style=" height: 25px; width:25px; margin-top:40%;" src="../images/arrow_drop_down.png"></i></a>');
document.write('<div class="collapsible-body">');
document.write('<ul>');
document.write('<li><a class="margineMenu" href="iscriversi.html">Come iscriversi</a></li>');
document.write('<li><a class="margineMenu" href="domande.html">Domande frequenti - FAQs</a></li>');
document.write('<li><a class="margineMenu" href="dateRicordare.html">Date da ricordare</a></li>');
document.write('<li><a class="margineMenu" href="hotel.html">Hotel / B&amp;B / Camper</a></li>');
document.write('<li><a class="margineMenu" href="affittaBici.html">Affitta una bici</a></li>');
document.write('</ul>');
document.write('</div>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="no-padding">');
document.write('<ul class="collapsible collapsible-accordion">');
document.write('<li>');
document.write('<a class="collapsible-header">Percorsi<i><img style=" height: 25px; width:25px; margin-top:40%;" src="../images/arrow_drop_down.png"></i></a>');
document.write('<div class="collapsible-body">');
document.write('<ul>');
document.write('<li><a class="margineMenu" href="salite.html">Salite</a></li>');
document.write('<li><a class="margineMenu" href="tabelleMarcia.html">Tabelle di marcia</a></li>');
document.write('<li><a class="margineMenu" href="ristori.html">Ristori</a></li>');
document.write('</ul>');
document.write('</div>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li><a href="classifiche.html">Classifiche</a></li>');
document.write('<li><a href="maglie.html">Maglie</a></li>');
document.write('<li><a href="circuiti.html">Circuiti</a></li>');
document.write('<li><a href="news.html">News</a></li>');
document.write('<li><a href="contatti.html">Contatti</a></li>');
document.write('</ul>');
document.write('<!-- Menu classico-->');
document.write('<ul class="right hide-on-med-and-down">');
document.write('<li><a href="../index.html">Home</a></li>');
document.write('<li><a class="dropdown-button" href="#!" data-activates="dropdown1">Edizione 2018<i class="right"><img style=" height: 25px; width:25px; margin-top:40%;" src="../images/arrow_drop_down.png"></i></a></li>');
document.write('<ul id="dropdown1" class="dropdown-content">');
document.write('<li><a href="iscriversi.html">Come iscriversi</a></li>');
document.write('<li><a href="domande.html">Domande frequenti - FAQs</a></li>');
document.write('<li><a href="dateRicordare.html">Date da ricordare</a></li>');
document.write('<li><a href="hotel.html">Hotel / B&amp;B / Camper</a></li>');
document.write('<li><a href="affittaBici.html">Affitta una bici</a></li>');
document.write('</ul>');
document.write('<li><a class="dropdown-button" href="#!" data-activates="dropdown1">Percorsi<i class="right"><img style=" height: 25px; width:25px; margin-top:40%;" src="../images/arrow_drop_down.png"></i></a></li>');
document.write('<ul id="dropdown1" class="dropdown-content">');
document.write('<li><a href="salite.html">Salite</a></li>');
document.write('<li><a href="tabelleMarcia.html">Tabelle di marcia</a></li>');
document.write('<li><a href="ristori.html">Ristori</a></li>');
document.write('</ul>');
document.write('<li><a href="classifiche.html">Classifiche</a></li>');
document.write('<li><a href="maglie.html">Maglie</a></li>');
document.write('<li><a href="circuiti.html">Circuiti</a></li>');
document.write('<li><a href="news.html">News</a></li>');
document.write('<li><a href="contatti.html">Contatti</a></li>');
document.write('</ul>');
document.write('<a href="#" data-activates="slide-out" class="button-collapse"><i><img style=" height: 25px; width:25px; margin-top:25%;" src="../images/menu.png"></i></a>');
document.write('</nav>');
